name: restaurant_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  android_alarm_manager_plus: ^3.0.2
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  http: ^1.1.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/restaurant.json
